export const STATES = [
  'All States',
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'FCT - Abuja',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara'
];

// Updated marketplace categories with new trades and emojis
export const CATEGORIES = [
  { name: 'Brand-new Phones & Accessories', icon: '🆕' },
  { name: 'Second-hand Phones', icon: '📱' },
  { name: 'Computers & Accessories', icon: '💻' },
  { name: 'Solar & Generators', icon: '🔋' },
  { name: 'Groceries & Provisions', icon: '🛒' },
  { name: 'Fashion & Clothing', icon: '👗' },
  { name: 'Car Sales', icon: '🚗' },
  { name: 'Car Rentals', icon: '🔑' },
  { name: 'House Sales', icon: '🏠' },
  { name: 'Land Sales', icon: '🌍' },
  { name: 'Furniture & Home Sales', icon: '🛋️' },
  { name: 'Kitchen & Home Appliances', icon: '🍳' },
  { name: 'Event Planning & Rentals', icon: '🎉' },
  { name: 'Poultry Sales', icon: '🐔' },
  { name: 'Beauty & Bodycare', icon: '💄' },
  { name: 'Gaming Console', icon: '🎮' },
  { name: 'Photography & Video', icon: '📸' }
];

export const SAFETY_TEXT = 'Payments happen outside the platform (WhatsApp, bank transfer, OPay, PalmPay). PeezuHub does not hold funds — deal at your own risk and verify sellers.';

export const SAFETY_TIPS = [
  'Verify seller via reviews/live photos.',
  'Never send money upfront (No "Pay before Delivery").',
  'Meet in a public, well-lit place for physical inspections.',
  'Beware of deals that seem too good to be true.',
  'Report suspicious activity to peezutech@gmail.com',
];
